### ISSUE TITLE
Create the UI for the Blogs page 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [gdscsmit/gdscsmit.github.io#60]
### Description : 
- The blogs section is one of the most important part of the website.
- The page is created in such a way that, the `Editorial Team` of SMIT will create blogs in `Blogger`
- We'll are Blogger as the headless CMS to fetch blogs using API keys (Already Implemented)
- Once user clicks on a Blog, they'll be redirected to the `Blog.jsx` component. 
- All list of blogs should be displayed in `BlogPage.jsx` component

### Tasks :
- [ ] Create the UI for the `BlogPage.jsx` component
- [ ] Fix the background bug and use some gradients
- [x] Fetch all blogs from `Blogger` and display it in the UI
- [ ] Redirect to the `Blog.jsx` and display that particular blog in the page

**Comment by asheshmandal2003** [comment]
@pooranjoyb can I work on this?

**Comment by pooranjoyb** [comment]
> @pooranjoyb can I work on this?

Go for it! 🚀

**Comment by asheshmandal2003** [comment]
Can you provide me the blog fetching url?

**Comment by Kamalesh-Seervi** [comment]
can I work on this task ?

**Comment by pooranjoyb** [comment]
> Can you provide me the blog fetching url?

Well, I guess you'll have to work out with your own `Blogger` account :)

**Comment by asheshmandal2003** [comment]
Ok
